import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

shell = "/usr/bin/fish"

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

[window]
decorations = "None"
opacity = 0.75

[cursor]
style = { shape = "Block", blinking = "On" }
